# correctness
#./baseline ./../../test_case/tiny_graph.txt 1

# real graph

./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 1
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 2
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 3
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 4
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 5
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 6
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 7
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 8
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 9
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 10
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 11
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 12
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 13
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 14
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 15
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 16
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 17
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 18
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 19
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 20
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 21
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 22
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 23
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 24
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 25
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 26
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 27
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 28
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 29
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 30
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 31
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 32
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 33
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 34
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 35
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 36
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 37
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 38
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 39
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 40
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 41
./baseline ./../../test_case/real_graph/USA-road-d.BAY.out 42
